### ISSUE TITLE
Hi, This is not an issue really...

### ISSUE THREAD

**Issue by YSCHGroup** [rakijah/SideProjects#1]
I was wondering how to install the CSGOSquadButton? Would love to use it! Thanks in advance!

**Comment by rakijah** [comment]
Hello, 
the way you use this depends on whether you're using Chrome or Firefox. You use it through addons like (in my case) [Tampermonkey](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo) or [Greasemonkey](https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/) (for Firefox). After installing the addon, you should be able to install the script by going to the addons settings page. There's probably enough tutorials on how to install scripts on Youtube, as well.

Also, I updated the script a while ago since CSGOSquad got rebranded/renamed to CSGO-Stats, I just hadn't commited the changes yet.

Hope you can get it to work, just leave another comment if you need further help.
